version: '3.8'
services:
  nginx:
    image: nginx:stable
    ports: 
      - 127.0.0.1:80:80
    networks:
      - my_net
    volumes:
      - ${PWD}/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/www/index.php:/var/www/index.php
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ${PWD}/www/index.php:/var/www/index.php
    networks:
      - my_net
    healthcheck:
      test: curl --fail http://nginx | grep works
      interval: 5s
      retries: 5
      timeout: 5s

networks:
  my_net:
    driver: bridge